import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  try {
    const res = await fetch("https://fakestoreapi.com/products")
    const data = await res.json()

    if (!data) {
      return {
        notFound: true
      }
    }

    return {
      props: { products: data },
    }
  } catch {
    return {
      props: { products: null },
    }
  }
}

export default function Home({ products }: any) {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        {products && products.map((datas: any) => {
          return (
            <Link href={`/products/${datas.id}`} key={datas.id}>
              <h1>{datas.category}</h1>
              <img className={styles.image} src={datas.image} alt={datas.category} />
              <p className={styles.title}>{datas.title}</p>
              <p className={styles.price}>{datas.price}$</p>
            </Link>
          )
        })}
      </main>
    </>
  )
}
